### ISSUE TITLE
How to reproduce the submission of training resnet50 at DAWNBench

### ISSUE THREAD

**Issue by sleepfin** [fastai/imagenet-fast#15]
I am trying to reproduce the submission of training resnet50 in 2 h 57 min at DAWNBench.

https://dawn.cs.stanford.edu/benchmark/

I read the code here:

https://github.com/fastai/imagenet-fast/blob/c4b225555e333a1a2702d2b291b5082bfa6d6a0a/imagenet_nv/main.py

But I have no idea about the arguments to reproduce the result. Anyone helps me ?

How many epochs should I set to train resnet50 in 2 h 57 min ?

**Comment by yossibiton** [comment]
I don't think the full training code is publicly available, I am looking for it also

**Comment by brettkoonce** [comment]
@bearpelican rebuilt the code over here, you should use: https://github.com/diux-dev/imagenet18
