### ISSUE TITLE
DAWN 3 hr training version

### ISSUE THREAD

**Issue by garyhujingyao** [fastai/imagenet-fast#16]
Hi all,

I was trying to reproduce the 2:57:28 training time mentioned here [https://dawn.cs.stanford.edu/benchmark/#imagenet-train-time](url).

I was wondering which .py file should I use, imagenet_nv/main.py or imagenet_nv/fastai_imagenet.py?

Also, when I tried to run imagenet_nv/fastai_imagenet.py, I got the following error:

What I executed:

python fastai_imagenet.py $imagenetDir -a resnet18 --save-dir logs/ --prof

What I got:

Running script with args: Namespace(arch='resnet18', batch_size=256, cycle_len=1, data='/media/data001/jingyao/imagenet_object_localization/ILSVRC/Data/CLS-LOC/', dist_backend='nccl', dist_url='file://sync.file', epochs=90, fp16=False, loss_scale=1, lr=0.1, momentum=0.9, pretrained=False, print_freq=50, prof=True, rank=0, resume='', save_dir='logs/', sz=224, train_128=False, use_clr=None, use_tta=False, weight_decay=0.0001, workers=4, world_size=1)
Traceback (most recent call last):
  File "fastai_imagenet.py", line 354, in <module>
    main()
  File "fastai_imagenet.py", line 337, in main
    loss_scale=args.loss_scale, **sargs)
  File "/home/jingyao/Research/fastai/fastai/learner.py", line 302, in fit
    return self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
  File "/home/jingyao/Research/fastai/fastai/learner.py", line 249, in fit_gen
    swa_eval_freq=swa_eval_freq, **kwargs)
  File "/home/jingyao/Research/fastai/fastai/model.py", line 123, in fit
    model_stepper = stepper(model, opt.opt if hasattr(opt,'opt') else opt, crit, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'sampler'

I also realized that #9 has a similar issue, and can you @bearpelican look into it please? Any help would be much appreciated!

**Comment by garyhujingyao** [comment]
It seems that you can just follow the changes in #10 to address the unexpected keyword problem.

However, I am still wondering which program I should run for the 2:57:28 training time. Any suggestion would be appreciated.

**Comment by brettkoonce** [comment]
@bearpelican rebuilt the code over here, you should use: https://github.com/diux-dev/imagenet18

**Comment by garyhujingyao** [comment]
Thank you @brettkoonce !
