### ISSUE TITLE
Not able to run dawn_mod.py

### ISSUE THREAD

**Issue by awan-10** [fastai/imagenet-fast#9]
Hi Folks, thank you for doing this great work at fastai.

I am trying to reproduce the following
```
python dawn_mod.py ~/data/cifar10/ --save-dir ~/data/cf_train_save/wrn_v5 -a wrn_22 --fp16 --loss-scale 512 --epochs 1 --cycle-len 30 --lr 1.5 --wd 1e-4 --use-clr 20,20,0.95,0.85
```
and I am getting this error:
```
Traceback (most recent call last):
  File "dawn_mod.py", line 343, in <module>
    main()
  File "dawn_mod.py", line 329, in main
    **sargs)
  File "/home/ammar/.local/lib/python3.6/site-packages/fastai/learner.py", line 287, in fit
    return self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
  File "/home/ammar/.local/lib/python3.6/site-packages/fastai/learner.py", line 234, in fit_gen
    swa_eval_freq=swa_eval_freq, **kwargs)
  File "/home/ammar/.local/lib/python3.6/site-packages/fastai/model.py", line 112, in fit
    model_stepper = stepper(model, opt.opt if hasattr(opt,'opt') else opt, crit, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'sampler'
```

Any ideas? Has the API for fastai changed? I used pip install for all the dependencies and fastai itself.

**Comment by mklissa** [comment]
I get the same error.

**Comment by bearpelican** [comment]
Yup looks like you need to set trn_sampler at the ModelData level now.

Inside torch_loader function:
`if train_sampler is not None: data.trn_sampler = train_sampler`

**Comment by MaveriQ** [comment]
I am getting the same error with fastai_imagenet.py. Should I open another issue?

**Comment by mklissa** [comment]
To me it seems as though extra arguments are passed to the stepper through **kwargs - arguments that it is not supposed to receive.

**Comment by jiaweizzhao** [comment]
I got the same error with fastai_imagenet.py too. Did anyone solve this problem yet?

**Comment by brettkoonce** [comment]
Use the fastai git checkout mentioned in the readme (e.g do a git reset --hard SHA1) and then the rest should work.

**Comment by garyhujingyao** [comment]
@brettkoonce 
Hi, 

I did git reset --hard SHA1, but I got this error.

fatal: ambiguous argument 'SHA1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

I tried this command both in fastai/ git directory and imagenet-fast directory.

Can you link the readme file you are referring to?

**Comment by nebfield** [comment]
> @brettkoonce
> Hi,
> 
> I did git reset --hard SHA1, but I got this error.
> 
> fatal: ambiguous argument 'SHA1': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git [...] -- [...]'
> 
> I tried this command both in fastai/ git directory and imagenet-fast directory.
> 
> Can you link the readme file you are referring to?

Run `git reset -hard f9c3d22cdb79e9438c308e3baeb91f04944081fe` in the `fastai/` directory. Then run the scripts you need to in the imagenet-fast/ directory.

[Here is the README](https://github.com/fastai/imagenet-fast/blob/master/cifar10/dawn_submission/README.md) Brett mentioned.

**Comment by brettkoonce** [comment]
@nebfield Thanks!
